#!/bin/bash

# glibc mirror url
# url="http://archive.ubuntu.com/ubuntu/pool/main/g/glibc"
url="https://mirrors.tuna.tsinghua.edu.cn/ubuntu/pool/main/g/glibc"

# switch to download other type
perfix="libc6_"
postfix="\.deb"
pathInDeb="lib"

dbg_perfix="libc6-dbg_"
dbg_postfix="\.deb"
dbg_pathInDeb="usr/lib/debug/lib"

if [[ $# -ne 2 ]]; then
	echo "Usage: $0 dbPath all|bin|dbg"
	exit 1
fi

die() {
  echo >&2 $1
  exit 1
}

get_glibc_deb(){
    local file="$1"
    local tmp=`mktemp -d`
    local dirname=${file%${postfix}}
    dirname=${dirname#${perfix}}
    echo "$file"

    if [[ -d $dbPath/$dirname ]];then
        echo "Path $dbPath/$dirname has been exsited."
        echo "Skip."
        return
    fi

    echo "Getting $file"
    wget "$url/$file" -O "$tmp/pkg.deb" -q --tries=0 || die "Failed to download package from $url"
    pushd "$tmp" 1>/dev/null
    ar x "$tmp/pkg.deb" || die "ar failed"
    tar xf $tmp/data.tar.* || die "tar failed"
    popd 1>/dev/null
    local t=`ls $tmp/$pathInDeb | grep linux-gnu`
    mv "$tmp/$pathInDeb/$t" "$dbPath/$dirname/"
    rm -rf "$tmp"
}

get_glibc_all(){
    echo "Getting glibc index"
    local indexhtml=`mktemp`
    wget $url/ -O - -q | grep -o "href=\"${perfix}[^\"]*${postfix}\"" > $indexhtml
    local files=`cat $indexhtml  | awk -F '"' '{print $2}'`
    local total=`wc -l $indexhtml | awk '{print $1}'`
    rm $indexhtml
    echo "Start to download"
    local i=0
    for file in $files ; do
        echo -n -e "\033[35m\033[1m[$i/$total]\033[0m "
        get_glibc_deb $file
        ((i++))
    done
    echo "Finish."
}


get_glibc_dbg_deb(){
    local file="$1"
    local tmp=`mktemp -d`
    local dirname=${file%${dbg_postfix}}
    dirname=${dirname#${dbg_perfix}}
    echo "$file"

    if [[ ! -d $dbPath/$dirname ]];then
        echo "Path $dbPath/$dirname doesn't exsited."
        echo "Skip."
        return
    fi

    if [[ -d $dbPath/$dirname/.debug ]];then
        echo "Path $dbPath/$dirname/.debug has been exsited."
        echo "Skip."
        return
    fi

    echo "Getting $file"
    wget "$url/$file" -O "$tmp/pkg.deb" -q --tries=0 || die "Failed to download package from $url"
    pushd "$tmp" 1>/dev/null
    ar x "$tmp/pkg.deb" || die "ar failed"
    tar xf $tmp/data.tar.* || die "tar failed"
    popd 1>/dev/null
    local t=`ls $tmp/$dbg_pathInDeb | grep linux-gnu`
    mv "$tmp/$dbg_pathInDeb/$t" "$dbPath/$dirname/.debug"
    rm -rf "$tmp"
}

get_glibc_dbg_all(){
    echo "Getting glibc-dbg index"
    local indexhtml=`mktemp`
    wget $url/ -O - -q | grep -o "href=\"${dbg_perfix}[^\"]*${dbg_postfix}\"" > $indexhtml
    local files=`cat $indexhtml  | awk -F '"' '{print $2}'`
    local total=`wc -l $indexhtml | awk '{print $1}'`
    rm $indexhtml
    echo "Start to download"
    local i=0
    for file in $files ; do
        echo -n -e "\033[35m\033[1m[$i/$total]\033[0m "
        get_glibc_dbg_deb $file
        ((i++))
    done
    echo "Finish."
}

dbPath="$1"
mkdir -p $dbPath

if [ "$2"x == "all"x ];then
    get_glibc_all
    get_glibc_dbg_all
elif [ "$2"x == "bin"x ];then
    get_glibc_all
elif [ "$2"x == "dbg"x ];then
    get_glibc_dbg_all
else
    echo "Unknow parameter \"$2\"."
fi
